# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 23:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time2meeting', '0002_remove_events_time_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeslot', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time2meeting.Events')),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeslot', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time2meeting.Events')),
            ],
        ),
        migrations.RemoveField(
            model_name='timeslots',
            name='event_participant',
        ),
        migrations.AddField(
            model_name='timeslots',
            name='is_decision',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timeslots',
            name='is_result',
            field=models.IntegerField(default=0),
        ),
    ]
