# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_event', '0002_remove_timeslots_event_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslots',
            name='is_decision',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timeslots',
            name='is_result',
            field=models.IntegerField(default=0),
        ),
    ]
