#!/bin/sh
#
# DO NOT CHANGE THE EXECUTE RIGHT OF THIS SCRIPT!!!
#
# a pre-commit git-hook to do static analysis with pylint before commiting.
#

# check whether in a virtual env, if yes, then add it to PATH.
if [ ! -z $VIRTUAL_ENV ]; then
    PATH=$VIRTUAL_ENV/bin:$PATH
fi

# get the dir of python files among the committed files.
PYFILES=$(git diff --name-only --staged | grep "\.py$")

# if there is no python file, then just do the commit.
if [ -z $PYFILES ]; then
    exit 0
else
    echo "\nStarting static analysis on your code...\n"
    # use pylint to do the static analysis on these python files.
    pylint $PYFILES
    # catch the exit code of analysis result (0 means no error).
    OUT=$?
    if [ $OUT -eq 0 ]; then
        echo "\nYour code looks great!\n"
        exit 0
    else
        echo "SORRY! STATIC ANALYSIS FAILED!"
        echo "You can not commit until your code pass the static analysis!\n"
        echo "Or you can commit only non-python files\n"
        exit 1
    fi
fi
